// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SubGuard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220165704_changenullableprop")]
    partial class changenullableprop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresContract")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Streaming",
                            ColorCode = "#E50914",
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(6048),
                            IsDeleted = false,
                            Name = "Netflix",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 2,
                            Category = "GSM",
                            ColorCode = "#FFC900",
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(6051),
                            IsDeleted = false,
                            Name = "Turkcell",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 3,
                            Category = "Music",
                            ColorCode = "#1DB954",
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(6053),
                            IsDeleted = false,
                            Name = "Spotify",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cloud",
                            ColorCode = "#000000",
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(6054),
                            IsDeleted = false,
                            Name = "Apple iCloud",
                            RequiresContract = false
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCycleDays")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCycleDays = 30,
                            CatalogId = 1,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9343),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Temel",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 2,
                            BillingCycleDays = 30,
                            CatalogId = 1,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9345),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Standart",
                            Price = 176.99m
                        },
                        new
                        {
                            Id = 3,
                            BillingCycleDays = 30,
                            CatalogId = 1,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9347),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Özel",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 4,
                            BillingCycleDays = 30,
                            CatalogId = 2,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9348),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 5,
                            BillingCycleDays = 30,
                            CatalogId = 2,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9350),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Duo",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 6,
                            BillingCycleDays = 30,
                            CatalogId = 2,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9351),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 7,
                            BillingCycleDays = 30,
                            CatalogId = 3,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9352),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Platinum 20GB",
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 8,
                            BillingCycleDays = 30,
                            CatalogId = 3,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9354),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Gülümseten 10GB",
                            Price = 220.00m
                        },
                        new
                        {
                            Id = 9,
                            BillingCycleDays = 30,
                            CatalogId = 4,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9355),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "50 GB",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = 10,
                            BillingCycleDays = 30,
                            CatalogId = 4,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9356),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "200 GB",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 11,
                            BillingCycleDays = 30,
                            CatalogId = 4,
                            CreatedDate = new DateTime(2025, 12, 20, 16, 57, 4, 86, DateTimeKind.Utc).AddTicks(9358),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "2 TB",
                            Price = 9.99m
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<int?>("CatalogId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasContract")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SharedWithJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageHistoryJson")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany("Plans")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
