// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SubGuard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219153158_AddPlansSeedData")]
    partial class AddPlansSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresContract")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Streaming",
                            ColorCode = "#E50914",
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(2253),
                            IsDeleted = false,
                            Name = "Netflix",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 2,
                            Category = "GSM",
                            ColorCode = "#FFC900",
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(2255),
                            IsDeleted = false,
                            Name = "Turkcell",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 3,
                            Category = "Music",
                            ColorCode = "#1DB954",
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(2257),
                            IsDeleted = false,
                            Name = "Spotify",
                            RequiresContract = false
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCycleDays")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCycleDays = 30,
                            CatalogId = 1,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5114),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Temel",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 2,
                            BillingCycleDays = 30,
                            CatalogId = 1,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5116),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Standart",
                            Price = 176.99m
                        },
                        new
                        {
                            Id = 3,
                            BillingCycleDays = 30,
                            CatalogId = 1,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5117),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Özel",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 4,
                            BillingCycleDays = 30,
                            CatalogId = 2,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5118),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 5,
                            BillingCycleDays = 30,
                            CatalogId = 2,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5120),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Duo",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 6,
                            BillingCycleDays = 30,
                            CatalogId = 2,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5121),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 7,
                            BillingCycleDays = 30,
                            CatalogId = 3,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5122),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Platinum 20GB",
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 8,
                            BillingCycleDays = 30,
                            CatalogId = 3,
                            CreatedDate = new DateTime(2025, 12, 19, 15, 31, 58, 468, DateTimeKind.Utc).AddTicks(5124),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Gülümseten 10GB",
                            Price = 220.00m
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany("Plans")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
