// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SubGuard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311121045_AddNotificationIsRead")]
    partial class AddNotificationIsRead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresContract")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "Streaming",
                            ColorCode = "#E50914",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3000),
                            IsDeleted = false,
                            LogoUrl = "netflix_logo",
                            Name = "Netflix",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 102,
                            Category = "Streaming",
                            ColorCode = "#113CCF",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3007),
                            IsDeleted = false,
                            LogoUrl = "disney_logo",
                            Name = "Disney+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 103,
                            Category = "Streaming",
                            ColorCode = "#11D6D4",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3009),
                            IsDeleted = false,
                            LogoUrl = "blutv_logo",
                            Name = "BluTV",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 104,
                            Category = "Streaming",
                            ColorCode = "#00A8E1",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3010),
                            IsDeleted = false,
                            LogoUrl = "prime_logo",
                            Name = "Amazon Prime",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 105,
                            Category = "Streaming",
                            ColorCode = "#FFD600",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3011),
                            IsDeleted = false,
                            LogoUrl = "exxen_logo",
                            Name = "Exxen",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 106,
                            Category = "Streaming",
                            ColorCode = "#191919",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3012),
                            IsDeleted = false,
                            LogoUrl = "mubi_logo",
                            Name = "MUBI",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 107,
                            Category = "Streaming",
                            ColorCode = "#592878",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3013),
                            IsDeleted = false,
                            LogoUrl = "tod_logo",
                            Name = "TOD (beIN)",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 108,
                            Category = "Streaming",
                            ColorCode = "#FF0000",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3014),
                            IsDeleted = false,
                            LogoUrl = "youtube_logo",
                            Name = "YouTube Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 109,
                            Category = "Streaming",
                            ColorCode = "#FF0000",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3015),
                            IsDeleted = false,
                            LogoUrl = "gain_logo",
                            Name = "Gain",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 201,
                            Category = "Music",
                            ColorCode = "#1DB954",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3039),
                            IsDeleted = false,
                            LogoUrl = "spotify_logo",
                            Name = "Spotify",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 202,
                            Category = "Music",
                            ColorCode = "#FA243C",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3040),
                            IsDeleted = false,
                            LogoUrl = "applemusic_logo",
                            Name = "Apple Music",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 203,
                            Category = "Music",
                            ColorCode = "#F39200",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3041),
                            IsDeleted = false,
                            LogoUrl = "fizy_logo",
                            Name = "Fizy",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 204,
                            Category = "Music",
                            ColorCode = "#EF5466",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3041),
                            IsDeleted = false,
                            LogoUrl = "deezer_logo",
                            Name = "Deezer",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 301,
                            Category = "Gaming",
                            ColorCode = "#00439C",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3045),
                            IsDeleted = false,
                            LogoUrl = "psplus_logo",
                            Name = "PlayStation Plus",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 302,
                            Category = "Gaming",
                            ColorCode = "#107C10",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3046),
                            IsDeleted = false,
                            LogoUrl = "gamepass_logo",
                            Name = "Xbox Game Pass",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 303,
                            Category = "Gaming",
                            ColorCode = "#76B900",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3047),
                            IsDeleted = false,
                            LogoUrl = "gfn_logo",
                            Name = "GeForce Now",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 304,
                            Category = "Gaming",
                            ColorCode = "#5865F2",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3048),
                            IsDeleted = false,
                            LogoUrl = "discord_logo",
                            Name = "Discord Nitro",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 401,
                            Category = "Shopping",
                            ColorCode = "#FF6000",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3052),
                            IsDeleted = false,
                            LogoUrl = "hepsiburada_logo",
                            Name = "Hepsiburada Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 402,
                            Category = "Food",
                            ColorCode = "#EA004B",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3053),
                            IsDeleted = false,
                            LogoUrl = "yemeksepeti_logo",
                            Name = "Yemeksepeti Club",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 403,
                            Category = "Food",
                            ColorCode = "#5D3EB2",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3054),
                            IsDeleted = false,
                            LogoUrl = "getir_logo",
                            Name = "Getir",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 501,
                            Category = "Cloud",
                            ColorCode = "#007AFF",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3057),
                            IsDeleted = false,
                            LogoUrl = "icloud_logo",
                            Name = "Apple iCloud",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 502,
                            Category = "Cloud",
                            ColorCode = "#4285F4",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3058),
                            IsDeleted = false,
                            LogoUrl = "googleone_logo",
                            Name = "Google One",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 503,
                            Category = "Cloud",
                            ColorCode = "#EA3E23",
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 375, DateTimeKind.Utc).AddTicks(3059),
                            IsDeleted = false,
                            LogoUrl = "office_logo",
                            Name = "Microsoft 365",
                            RequiresContract = true
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.NotificationQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionId");

                    b.HasIndex("UserId", "IsSent")
                        .HasDatabaseName("IX_NotificationQueue_UserId_IsSent");

                    b.HasIndex("UserId", "UserSubscriptionId", "ScheduledDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_NotificationQueue_UserId_SubscriptionId_ScheduledDate");

                    b.ToTable("NotificationQueues", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCycleDays")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(729),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Temel Plan",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 1002,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(736),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Standart Plan",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 1003,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(738),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Özel Plan",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 2001,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(739),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 2002,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(740),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Öğrenci",
                            Price = 32.99m
                        },
                        new
                        {
                            Id = 2003,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(741),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Duo",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 2004,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(742),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 3001,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(743),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 57.99m
                        },
                        new
                        {
                            Id = 3002,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(744),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 115.99m
                        },
                        new
                        {
                            Id = 3003,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 3, 11, 12, 10, 45, 376, DateTimeKind.Utc).AddTicks(745),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Öğrenci",
                            Price = 37.99m
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_RefreshTokens_Code");

                    b.HasIndex("Code", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_Code_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<int?>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasContract")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SharedWithJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageHistoryJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSubscriptions_UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserSubscriptions_UserId_Name");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubGuard.Core.Entities.NotificationQueue", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.UserSubscription", "UserSubscription")
                        .WithMany()
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany("Plans")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
