// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SubGuard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404064449_AllowDuplicateSubscriptionNames")]
    partial class AllowDuplicateSubscriptionNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("BudgetAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("BudgetAlertThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ExpoPushToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("MonthlyBudgetCurrency")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("NotifEmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifPushEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("NotifReminderDays")
                        .HasColumnType("integer");

                    b.Property<int>("NotifyHour")
                        .HasColumnType("integer");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OtpFailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("OtpToken")
                        .HasColumnType("text");

                    b.Property<string>("OtpType")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("SharedAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresContract")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "Streaming",
                            ColorCode = "#E50914",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5562),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=netflix.com",
                            Name = "Netflix",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 102,
                            Category = "Streaming",
                            ColorCode = "#113CCF",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5573),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=disneyplus.com",
                            Name = "Disney+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 103,
                            Category = "Streaming",
                            ColorCode = "#11D6D4",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5624),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=blutv.com",
                            Name = "BluTV",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 104,
                            Category = "Streaming",
                            ColorCode = "#00A8E1",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5626),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=primevideo.com",
                            Name = "Amazon Prime",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 105,
                            Category = "Streaming",
                            ColorCode = "#FFD600",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5627),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=exxen.com",
                            Name = "Exxen",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 106,
                            Category = "Streaming",
                            ColorCode = "#191919",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5629),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=mubi.com",
                            Name = "MUBI",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 107,
                            Category = "Streaming",
                            ColorCode = "#592878",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5632),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=tod.tv",
                            Name = "TOD (beIN)",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 108,
                            Category = "Streaming",
                            ColorCode = "#FF0000",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5633),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=youtube.com",
                            Name = "YouTube Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 109,
                            Category = "Streaming",
                            ColorCode = "#FF6A00",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5634),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=gain.tv",
                            Name = "Gain",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 110,
                            Category = "Streaming",
                            ColorCode = "#E8261A",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5635),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=puhutv.com",
                            Name = "Puhutv",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 111,
                            Category = "Streaming",
                            ColorCode = "#1A936F",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5636),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=tabii.com",
                            Name = "Tabii",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 112,
                            Category = "Streaming",
                            ColorCode = "#000000",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5637),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=apple.com",
                            Name = "Apple TV+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 113,
                            Category = "Streaming",
                            ColorCode = "#0064FF",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5639),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=paramountplus.com",
                            Name = "Paramount+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 114,
                            Category = "Streaming",
                            ColorCode = "#F47521",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5640),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=crunchyroll.com",
                            Name = "Crunchyroll",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 115,
                            Category = "Streaming",
                            ColorCode = "#009EDB",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5641),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=tvplus.com.tr",
                            Name = "Turkcell TV+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 201,
                            Category = "Music",
                            ColorCode = "#1DB954",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5663),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=spotify.com",
                            Name = "Spotify",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 202,
                            Category = "Music",
                            ColorCode = "#FA243C",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5664),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=music.apple.com",
                            Name = "Apple Music",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 203,
                            Category = "Music",
                            ColorCode = "#F39200",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5665),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=fizy.com",
                            Name = "Fizy",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 204,
                            Category = "Music",
                            ColorCode = "#EF5466",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5668),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=deezer.com",
                            Name = "Deezer",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 205,
                            Category = "Music",
                            ColorCode = "#000000",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5670),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=tidal.com",
                            Name = "Tidal",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 206,
                            Category = "Music",
                            ColorCode = "#FF6B35",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5672),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=muud.com.tr",
                            Name = "Muud",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 301,
                            Category = "Gaming",
                            ColorCode = "#00439C",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5677),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=playstation.com",
                            Name = "PlayStation Plus",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 302,
                            Category = "Gaming",
                            ColorCode = "#107C10",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5678),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=xbox.com",
                            Name = "Xbox Game Pass",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 303,
                            Category = "Gaming",
                            ColorCode = "#76B900",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5679),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=nvidia.com",
                            Name = "GeForce Now",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 304,
                            Category = "Gaming",
                            ColorCode = "#5865F2",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5680),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=discord.com",
                            Name = "Discord Nitro",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 305,
                            Category = "Gaming",
                            ColorCode = "#1B2838",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5681),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=steampowered.com",
                            Name = "Steam",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 306,
                            Category = "Gaming",
                            ColorCode = "#FF4747",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5683),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=ea.com",
                            Name = "EA Play",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 401,
                            Category = "Shopping",
                            ColorCode = "#FF6000",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5686),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=hepsiburada.com",
                            Name = "Hepsiburada Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 402,
                            Category = "Food",
                            ColorCode = "#EA004B",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5688),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=yemeksepeti.com",
                            Name = "Yemeksepeti Club",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 403,
                            Category = "Food",
                            ColorCode = "#5D3EB2",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5689),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=getir.com",
                            Name = "Getir",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 404,
                            Category = "Shopping",
                            ColorCode = "#F27A1A",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5727),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=trendyol.com",
                            Name = "Trendyol Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 501,
                            Category = "Cloud",
                            ColorCode = "#007AFF",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5731),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=icloud.com",
                            Name = "Apple iCloud",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 502,
                            Category = "Cloud",
                            ColorCode = "#4285F4",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5732),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=one.google.com",
                            Name = "Google One",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 503,
                            Category = "Cloud",
                            ColorCode = "#EA3E23",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5733),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=microsoft.com",
                            Name = "Microsoft 365",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 504,
                            Category = "Cloud",
                            ColorCode = "#0061FF",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5735),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=dropbox.com",
                            Name = "Dropbox",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 505,
                            Category = "Cloud",
                            ColorCode = "#FF0000",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5736),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=adobe.com",
                            Name = "Adobe Creative Cloud",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 506,
                            Category = "Cloud",
                            ColorCode = "#00C4CC",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5737),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=canva.com",
                            Name = "Canva Pro",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 507,
                            Category = "Cloud",
                            ColorCode = "#10A37F",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5738),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=openai.com",
                            Name = "ChatGPT Plus",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 508,
                            Category = "Cloud",
                            ColorCode = "#4687FF",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5739),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=nordvpn.com",
                            Name = "NordVPN",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 601,
                            Category = "Education",
                            ColorCode = "#58CC02",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5744),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=duolingo.com",
                            Name = "Duolingo Plus",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 602,
                            Category = "Education",
                            ColorCode = "#0A66C2",
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 138, DateTimeKind.Utc).AddTicks(5746),
                            IsDeleted = false,
                            LogoUrl = "https://www.google.com/s2/favicons?sz=128&domain=linkedin.com",
                            Name = "LinkedIn Premium",
                            RequiresContract = false
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.CategoryBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Category")
                        .IsUnique()
                        .HasDatabaseName("IX_CategoryBudgets_UserId_Category");

                    b.ToTable("CategoryBudgets");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.NotificationQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserSubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionId");

                    b.HasIndex("UserId", "IsSent")
                        .HasDatabaseName("IX_NotificationQueue_UserId_IsSent");

                    b.HasIndex("UserId", "UserSubscriptionId", "ScheduledDate", "Type")
                        .IsUnique()
                        .HasDatabaseName("UQ_NotificationQueue_UserId_SubscriptionId_ScheduledDate_Type");

                    b.ToTable("NotificationQueues", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCycleDays")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3022),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Temel Plan",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 1002,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3030),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Standart Plan",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 1003,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3032),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Özel Plan",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 2001,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3033),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 2002,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3034),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Öğrenci",
                            Price = 32.99m
                        },
                        new
                        {
                            Id = 2003,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3035),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Duo",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 2004,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3036),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 3001,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3037),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 57.99m
                        },
                        new
                        {
                            Id = 3002,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3038),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 115.99m
                        },
                        new
                        {
                            Id = 3003,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3039),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Öğrenci",
                            Price = 37.99m
                        },
                        new
                        {
                            Id = 4001,
                            BillingCycleDays = 30,
                            CatalogId = 110,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3040),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 4002,
                            BillingCycleDays = 30,
                            CatalogId = 110,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3041),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 4101,
                            BillingCycleDays = 30,
                            CatalogId = 111,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3042),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 4102,
                            BillingCycleDays = 30,
                            CatalogId = 111,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3043),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 4201,
                            BillingCycleDays = 30,
                            CatalogId = 112,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3044),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 4202,
                            BillingCycleDays = 30,
                            CatalogId = 112,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3045),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 4301,
                            BillingCycleDays = 30,
                            CatalogId = 113,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3046),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 4401,
                            BillingCycleDays = 30,
                            CatalogId = 114,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3047),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Fanatic",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 4402,
                            BillingCycleDays = 30,
                            CatalogId = 114,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3048),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Mega Fan",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 4501,
                            BillingCycleDays = 30,
                            CatalogId = 115,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3049),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 4502,
                            BillingCycleDays = 30,
                            CatalogId = 115,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3050),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 5001,
                            BillingCycleDays = 30,
                            CatalogId = 205,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3051),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 5002,
                            BillingCycleDays = 30,
                            CatalogId = 205,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3052),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 5101,
                            BillingCycleDays = 30,
                            CatalogId = 306,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3053),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "EA Play",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 5102,
                            BillingCycleDays = 30,
                            CatalogId = 306,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3054),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "EA Play Pro",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 5201,
                            BillingCycleDays = 30,
                            CatalogId = 404,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3056),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Premium Üyelik",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 5301,
                            BillingCycleDays = 30,
                            CatalogId = 504,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3057),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Plus (2 TB)",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 5302,
                            BillingCycleDays = 30,
                            CatalogId = 504,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3058),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Professional (3 TB)",
                            Price = 16.58m
                        },
                        new
                        {
                            Id = 5401,
                            BillingCycleDays = 30,
                            CatalogId = 505,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3059),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Tüm Uygulamalar",
                            Price = 54.99m
                        },
                        new
                        {
                            Id = 5402,
                            BillingCycleDays = 30,
                            CatalogId = 505,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3060),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Tek Uygulama",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = 5501,
                            BillingCycleDays = 30,
                            CatalogId = 506,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3061),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Pro",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 5601,
                            BillingCycleDays = 30,
                            CatalogId = 507,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3062),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Plus",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 5602,
                            BillingCycleDays = 30,
                            CatalogId = 507,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3063),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Pro",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 5701,
                            BillingCycleDays = 30,
                            CatalogId = 508,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3064),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Basic",
                            Price = 3.79m
                        },
                        new
                        {
                            Id = 5702,
                            BillingCycleDays = 30,
                            CatalogId = 508,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3065),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Plus",
                            Price = 4.79m
                        },
                        new
                        {
                            Id = 5801,
                            BillingCycleDays = 30,
                            CatalogId = 601,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3066),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Super",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 5802,
                            BillingCycleDays = 30,
                            CatalogId = 601,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3067),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Max",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 5901,
                            BillingCycleDays = 30,
                            CatalogId = 602,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3068),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Career",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 5902,
                            BillingCycleDays = 30,
                            CatalogId = 602,
                            CreatedDate = new DateTime(2026, 4, 4, 6, 44, 49, 139, DateTimeKind.Utc).AddTicks(3069),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Business",
                            Price = 59.99m
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_RefreshTokens_Code");

                    b.HasIndex("Expiration")
                        .HasDatabaseName("IX_RefreshTokens_Expiration");

                    b.HasIndex("Code", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_Code_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.RevokedUserEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RevokedUserEntries");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.SubscriptionShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharedUserEmail")
                        .HasColumnType("text");

                    b.Property<string>("SharedUserId")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "SharedUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_SubscriptionShares_SubId_UserId");

                    b.ToTable("SubscriptionShares");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.SubscriptionUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionUsageLogs");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccessUntilDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<int?>("BillingMonth")
                        .HasColumnType("integer");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstPaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasContract")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PausedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSubscriptions_UserId");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("IX_UserSubscriptions_UserId_Name");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubGuard.Core.Entities.NotificationQueue", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.UserSubscription", "UserSubscription")
                        .WithMany()
                        .HasForeignKey("UserSubscriptionId");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany("Plans")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.PriceHistory", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.UserSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubGuard.Core.Entities.SubscriptionShare", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.UserSubscription", "Subscription")
                        .WithMany("Shares")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.SubscriptionUsageLog", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.UserSubscription", "Subscription")
                        .WithMany("UsageLogs")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.Navigation("Shares");

                    b.Navigation("UsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
