using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SubGuard.Data.Migrations
{
    /// <summary>
    /// Adds schema elements that were missing from the DB due to the Designer.cs snapshot
    /// being synthesized ahead of actual migrations. Uses IF NOT EXISTS guards for safety.
    /// </summary>
    public partial class AddMissingSchemaFix : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── AspNetUsers: eksik kolonlar ────────────────────────────────────
            migrationBuilder.Sql(@"
                ALTER TABLE ""AspNetUsers""
                    ADD COLUMN IF NOT EXISTS ""BudgetAlertEnabled"" boolean NOT NULL DEFAULT false,
                    ADD COLUMN IF NOT EXISTS ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ADD COLUMN IF NOT EXISTS ""SharedAlertEnabled"" boolean NOT NULL DEFAULT false;
            ");

            // ── SubscriptionShares tablosu (yoksa oluştur) ─────────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""SubscriptionShares"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""SubscriptionId"" integer NOT NULL,
                    ""SharedUserId"" text NOT NULL,
                    ""SharedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedDate"" timestamp with time zone,
                    ""CreatedBy"" text,
                    ""UpdatedBy"" text,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    CONSTRAINT ""FK_SubscriptionShares_UserSubscriptions_SubscriptionId""
                        FOREIGN KEY (""SubscriptionId"")
                        REFERENCES ""UserSubscriptions"" (""Id"")
                        ON DELETE RESTRICT
                );
            ");

            // ── SubscriptionUsageLogs tablosu (yoksa oluştur) ─────────────────
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""SubscriptionUsageLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""SubscriptionId"" integer NOT NULL,
                    ""UserId"" text NOT NULL,
                    ""Note"" text,
                    ""Amount"" numeric,
                    ""Unit"" text,
                    ""LoggedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""CreatedDate"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedDate"" timestamp with time zone,
                    ""CreatedBy"" text,
                    ""UpdatedBy"" text,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    CONSTRAINT ""FK_SubscriptionUsageLogs_UserSubscriptions_SubscriptionId""
                        FOREIGN KEY (""SubscriptionId"")
                        REFERENCES ""UserSubscriptions"" (""Id"")
                        ON DELETE RESTRICT
                );
            ");

            // ── Indexes ────────────────────────────────────────────────────────
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_PriceHistories_SubscriptionId""
                    ON ""PriceHistories"" (""SubscriptionId"");
            ");

            // CategoryBudgets: yinelenen satırları temizle, sonra benzersiz index oluştur
            migrationBuilder.Sql(@"
                DELETE FROM ""CategoryBudgets"" cb
                WHERE cb.""Id"" NOT IN (
                    SELECT MAX(""Id"")
                    FROM ""CategoryBudgets""
                    GROUP BY ""UserId"", ""Category""
                );
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_CategoryBudgets_UserId_Category""
                    ON ""CategoryBudgets"" (""UserId"", ""Category"");
            ");

            migrationBuilder.Sql(@"
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_SubscriptionShares_SubId_UserId""
                    ON ""SubscriptionShares"" (""SubscriptionId"", ""SharedUserId"");
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_SubscriptionUsageLogs_SubscriptionId""
                    ON ""SubscriptionUsageLogs"" (""SubscriptionId"");
            ");

            // ── PriceHistories FK ──────────────────────────────────────────────
            // Constraint IF NOT EXISTS PostgreSQL 9.4+ desteklemez; önce kontrol et
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'FK_PriceHistories_UserSubscriptions_SubscriptionId'
                    ) THEN
                        ALTER TABLE ""PriceHistories""
                            ADD CONSTRAINT ""FK_PriceHistories_UserSubscriptions_SubscriptionId""
                            FOREIGN KEY (""SubscriptionId"")
                            REFERENCES ""UserSubscriptions"" (""Id"")
                            ON DELETE CASCADE;
                    END IF;
                END;
                $$;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""PriceHistories""
                    DROP CONSTRAINT IF EXISTS ""FK_PriceHistories_UserSubscriptions_SubscriptionId"";
            ");

            migrationBuilder.Sql(@"
                DROP INDEX IF EXISTS ""IX_SubscriptionUsageLogs_SubscriptionId"";
                DROP INDEX IF EXISTS ""IX_SubscriptionShares_SubId_UserId"";
                DROP INDEX IF EXISTS ""IX_CategoryBudgets_UserId_Category"";
                DROP INDEX IF EXISTS ""IX_PriceHistories_SubscriptionId"";
            ");

            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""SubscriptionUsageLogs"";
                DROP TABLE IF EXISTS ""SubscriptionShares"";
            ");

            migrationBuilder.Sql(@"
                ALTER TABLE ""AspNetUsers""
                    DROP COLUMN IF EXISTS ""SharedAlertEnabled"",
                    DROP COLUMN IF EXISTS ""CreatedDate"",
                    DROP COLUMN IF EXISTS ""BudgetAlertEnabled"";
            ");
        }
    }
}
