// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SubGuard.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316175823_SwitchLogoToGoogleFavicons")]
    partial class SwitchLogoToGoogleFavicons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ExpoPushToken")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MonthlyBudget")
                        .HasColumnType("numeric");

                    b.Property<string>("MonthlyBudgetCurrency")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresContract")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Catalogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Category = "Streaming",
                            ColorCode = "#E50914",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2287),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/netflix.com",
                            Name = "Netflix",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 102,
                            Category = "Streaming",
                            ColorCode = "#113CCF",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2289),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/disneyplus.com",
                            Name = "Disney+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 103,
                            Category = "Streaming",
                            ColorCode = "#11D6D4",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2290),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/blutv.com",
                            Name = "BluTV",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 104,
                            Category = "Streaming",
                            ColorCode = "#00A8E1",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2292),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/primevideo.com",
                            Name = "Amazon Prime",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 105,
                            Category = "Streaming",
                            ColorCode = "#FFD600",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2293),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/exxen.com",
                            Name = "Exxen",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 106,
                            Category = "Streaming",
                            ColorCode = "#191919",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2294),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/mubi.com",
                            Name = "MUBI",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 107,
                            Category = "Streaming",
                            ColorCode = "#592878",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2295),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/tod.tv",
                            Name = "TOD (beIN)",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 108,
                            Category = "Streaming",
                            ColorCode = "#FF0000",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2296),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/youtube.com",
                            Name = "YouTube Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 109,
                            Category = "Streaming",
                            ColorCode = "#FF6A00",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2297),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/gain.tv",
                            Name = "Gain",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 110,
                            Category = "Streaming",
                            ColorCode = "#E8261A",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2298),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/puhutv.com",
                            Name = "Puhutv",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 111,
                            Category = "Streaming",
                            ColorCode = "#1A936F",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2298),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/tabii.com",
                            Name = "Tabii",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 112,
                            Category = "Streaming",
                            ColorCode = "#000000",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2299),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/apple.com",
                            Name = "Apple TV+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 113,
                            Category = "Streaming",
                            ColorCode = "#0064FF",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2300),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/paramountplus.com",
                            Name = "Paramount+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 114,
                            Category = "Streaming",
                            ColorCode = "#F47521",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2301),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/crunchyroll.com",
                            Name = "Crunchyroll",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 115,
                            Category = "Streaming",
                            ColorCode = "#009EDB",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2302),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/tvplus.com.tr",
                            Name = "Turkcell TV+",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 201,
                            Category = "Music",
                            ColorCode = "#1DB954",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2323),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/spotify.com",
                            Name = "Spotify",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 202,
                            Category = "Music",
                            ColorCode = "#FA243C",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2324),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/apple.com",
                            Name = "Apple Music",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 203,
                            Category = "Music",
                            ColorCode = "#F39200",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2325),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/fizy.com",
                            Name = "Fizy",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 204,
                            Category = "Music",
                            ColorCode = "#EF5466",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2326),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/deezer.com",
                            Name = "Deezer",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 205,
                            Category = "Music",
                            ColorCode = "#000000",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2327),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/tidal.com",
                            Name = "Tidal",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 206,
                            Category = "Music",
                            ColorCode = "#FF6B35",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2328),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/muud.com.tr",
                            Name = "Muud",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 301,
                            Category = "Gaming",
                            ColorCode = "#00439C",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2331),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/playstation.com",
                            Name = "PlayStation Plus",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 302,
                            Category = "Gaming",
                            ColorCode = "#107C10",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2332),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/xbox.com",
                            Name = "Xbox Game Pass",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 303,
                            Category = "Gaming",
                            ColorCode = "#76B900",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2333),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/nvidia.com",
                            Name = "GeForce Now",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 304,
                            Category = "Gaming",
                            ColorCode = "#5865F2",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2334),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/discord.com",
                            Name = "Discord Nitro",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 305,
                            Category = "Gaming",
                            ColorCode = "#1B2838",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2335),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/steampowered.com",
                            Name = "Steam",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 306,
                            Category = "Gaming",
                            ColorCode = "#FF4747",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2336),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/ea.com",
                            Name = "EA Play",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 401,
                            Category = "Shopping",
                            ColorCode = "#FF6000",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2377),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/hepsiburada.com",
                            Name = "Hepsiburada Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 402,
                            Category = "Food",
                            ColorCode = "#EA004B",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2378),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/yemeksepeti.com",
                            Name = "Yemeksepeti Club",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 403,
                            Category = "Food",
                            ColorCode = "#5D3EB2",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2379),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/getir.com",
                            Name = "Getir",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 404,
                            Category = "Shopping",
                            ColorCode = "#F27A1A",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2380),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/trendyol.com",
                            Name = "Trendyol Premium",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 501,
                            Category = "Cloud",
                            ColorCode = "#007AFF",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2383),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/icloud.com",
                            Name = "Apple iCloud",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 502,
                            Category = "Cloud",
                            ColorCode = "#4285F4",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2384),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/google.com",
                            Name = "Google One",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 503,
                            Category = "Cloud",
                            ColorCode = "#EA3E23",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2385),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/microsoft.com",
                            Name = "Microsoft 365",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 504,
                            Category = "Cloud",
                            ColorCode = "#0061FF",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2386),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/dropbox.com",
                            Name = "Dropbox",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 505,
                            Category = "Cloud",
                            ColorCode = "#FF0000",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2387),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/adobe.com",
                            Name = "Adobe Creative Cloud",
                            RequiresContract = true
                        },
                        new
                        {
                            Id = 506,
                            Category = "Cloud",
                            ColorCode = "#00C4CC",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2388),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/canva.com",
                            Name = "Canva Pro",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 507,
                            Category = "Cloud",
                            ColorCode = "#10A37F",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2389),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/openai.com",
                            Name = "ChatGPT Plus",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 508,
                            Category = "Cloud",
                            ColorCode = "#4687FF",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2390),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/nordvpn.com",
                            Name = "NordVPN",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 601,
                            Category = "Education",
                            ColorCode = "#58CC02",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2395),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/duolingo.com",
                            Name = "Duolingo Plus",
                            RequiresContract = false
                        },
                        new
                        {
                            Id = 602,
                            Category = "Education",
                            ColorCode = "#0A66C2",
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(2395),
                            IsDeleted = false,
                            LogoUrl = "https://logo.clearbit.com/linkedin.com",
                            Name = "LinkedIn Premium",
                            RequiresContract = false
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.NotificationQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionId");

                    b.HasIndex("UserId", "IsSent")
                        .HasDatabaseName("IX_NotificationQueue_UserId_IsSent");

                    b.HasIndex("UserId", "UserSubscriptionId", "ScheduledDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_NotificationQueue_UserId_SubscriptionId_ScheduledDate");

                    b.ToTable("NotificationQueues", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCycleDays")
                        .HasColumnType("integer");

                    b.Property<int>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9177),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Temel Plan",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 1002,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9184),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Standart Plan",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = 1003,
                            BillingCycleDays = 30,
                            CatalogId = 101,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9185),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Özel Plan",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 2001,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9187),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 2002,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9188),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Öğrenci",
                            Price = 32.99m
                        },
                        new
                        {
                            Id = 2003,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9189),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Duo",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 2004,
                            BillingCycleDays = 30,
                            CatalogId = 201,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9190),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 3001,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9191),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 57.99m
                        },
                        new
                        {
                            Id = 3002,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9192),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 115.99m
                        },
                        new
                        {
                            Id = 3003,
                            BillingCycleDays = 30,
                            CatalogId = 108,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9193),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Öğrenci",
                            Price = 37.99m
                        },
                        new
                        {
                            Id = 4001,
                            BillingCycleDays = 30,
                            CatalogId = 110,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9194),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 4002,
                            BillingCycleDays = 30,
                            CatalogId = 110,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9195),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 4101,
                            BillingCycleDays = 30,
                            CatalogId = 111,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9196),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 4102,
                            BillingCycleDays = 30,
                            CatalogId = 111,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9197),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 4201,
                            BillingCycleDays = 30,
                            CatalogId = 112,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9198),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 4202,
                            BillingCycleDays = 30,
                            CatalogId = 112,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9199),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 4301,
                            BillingCycleDays = 30,
                            CatalogId = 113,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9200),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 4401,
                            BillingCycleDays = 30,
                            CatalogId = 114,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9201),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Fanatic",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 4402,
                            BillingCycleDays = 30,
                            CatalogId = 114,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9202),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Mega Fan",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 4501,
                            BillingCycleDays = 30,
                            CatalogId = 115,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9203),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 4502,
                            BillingCycleDays = 30,
                            CatalogId = 115,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9204),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 5001,
                            BillingCycleDays = 30,
                            CatalogId = 205,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9205),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Bireysel",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 5002,
                            BillingCycleDays = 30,
                            CatalogId = 205,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9206),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Aile",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 5101,
                            BillingCycleDays = 30,
                            CatalogId = 306,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9207),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "EA Play",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 5102,
                            BillingCycleDays = 30,
                            CatalogId = 306,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9208),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "EA Play Pro",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 5201,
                            BillingCycleDays = 30,
                            CatalogId = 404,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9209),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Premium Üyelik",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 5301,
                            BillingCycleDays = 30,
                            CatalogId = 504,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9210),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Plus (2 TB)",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 5302,
                            BillingCycleDays = 30,
                            CatalogId = 504,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9211),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Professional (3 TB)",
                            Price = 16.58m
                        },
                        new
                        {
                            Id = 5401,
                            BillingCycleDays = 30,
                            CatalogId = 505,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9212),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Tüm Uygulamalar",
                            Price = 54.99m
                        },
                        new
                        {
                            Id = 5402,
                            BillingCycleDays = 30,
                            CatalogId = 505,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9213),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Tek Uygulama",
                            Price = 20.99m
                        },
                        new
                        {
                            Id = 5501,
                            BillingCycleDays = 30,
                            CatalogId = 506,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9214),
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "Pro",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 5601,
                            BillingCycleDays = 30,
                            CatalogId = 507,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9215),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Plus",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 5602,
                            BillingCycleDays = 30,
                            CatalogId = 507,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9216),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Pro",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 5701,
                            BillingCycleDays = 30,
                            CatalogId = 508,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9217),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Basic",
                            Price = 3.79m
                        },
                        new
                        {
                            Id = 5702,
                            BillingCycleDays = 30,
                            CatalogId = 508,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9218),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Plus",
                            Price = 4.79m
                        },
                        new
                        {
                            Id = 5801,
                            BillingCycleDays = 30,
                            CatalogId = 601,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9219),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Super",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 5802,
                            BillingCycleDays = 30,
                            CatalogId = 601,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9220),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Max",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 5901,
                            BillingCycleDays = 30,
                            CatalogId = 602,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9221),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Career",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 5902,
                            BillingCycleDays = 30,
                            CatalogId = 602,
                            CreatedDate = new DateTime(2026, 3, 16, 17, 58, 23, 296, DateTimeKind.Utc).AddTicks(9222),
                            Currency = "USD",
                            IsDeleted = false,
                            Name = "Business",
                            Price = 59.99m
                        });
                });

            modelBuilder.Entity("SubGuard.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_RefreshTokens_Code");

                    b.HasIndex("Code", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_Code_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingDay")
                        .HasColumnType("integer");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CatalogId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasContract")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PausedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SharedWithJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageHistoryJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSubscriptions_UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserSubscriptions_UserId_Name");

                    b.ToTable("UserSubscriptions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubGuard.Core.Entities.NotificationQueue", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.UserSubscription", "UserSubscription")
                        .WithMany()
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Plan", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany("Plans")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.UserSubscription", b =>
                {
                    b.HasOne("SubGuard.Core.Entities.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("SubGuard.Core.Entities.Catalog", b =>
                {
                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
